version: '3'

services:
  db:
    container_name: nextcloud-mariadb
    build: ./db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always
    volumes:
      - cache:/data

  app:
    container_name: nextcloud-app
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  web:
    container_name: nextcloud-nginx
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    env_file:
      - nginx.env
    depends_on:
      - app
    networks:
      - proxy-net
      - default

  proxy:
    container_name: nextcloud-proxy
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-net
    depends_on:
      - omgwtfssl

  omgwtfssl:
    container_name: nextcloud-ssl
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    env_file:
      - sslcert.env
    networks:
      - proxy-net

volumes:
  # database volume
  # use a high performance drive
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/nextcloud/db
  # nextcloud data volume
  # use drive pool, this will be huge
  nextcloud:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/nextcloud/data
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/nextcloud/certs
  vhost.d:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/nextcloud/vhost
  html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/nextcloud/html
  # redis cache volume
  # definitely use a high performance drive
  cache:

networks:
  proxy-net:
